name: EKS Cluster Deployment and Nginx Pod Deployment

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "ap-south-1"
  CLUSTER_NAME: "my-eks-cluster"
  K8S_NAMESPACE: "default"

jobs:
  terraform-eks:
    name: Create EKS Cluster Using Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Initialize Terraform
      working-directory: EKS-Cluster
      run: terraform init

    - name: Apply Terraform Plan
      working-directory: EKS-Cluster
      run: terraform apply -auto-approve

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Configure kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

    - name: Verify kubectl connectivity
      run: kubectl get nodes

  deploy-nginx:
    name: Deploy Nginx to EKS
    runs-on: ubuntu-latest
    needs: terraform-eks

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Configure kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

    - name: Apply Nginx Deployment to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml --namespace ${{ env.K8S_NAMESPACE }}

    - name: Verify Nginx Deployment
      run: |
        kubectl get pods --namespace ${{ env.K8S_NAMESPACE }}
